# Generated by Django 2.2.5 on 2019-12-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Message', verbose_name='Последнее прочитанное сообщение'),
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.TextField(verbose_name='Новые сообщения'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Аватрака пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=16, verbose_name='Никнейм пользователя'),
        ),
    ]
