# Generated by Django 2.2.5 on 2019-12-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20191205_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Message', verbose_name='id сообщения'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=16, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(verbose_name='Ссылка на вложение'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='id ользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False, verbose_name='Групповой чат'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(default='null', max_length=32, verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=16, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время отправкивки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Содержание сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='id пользователя'),
        ),
    ]
